# Generated by Django 5.2.17 on 2026-10-06 16:33

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Mitarbeiter')], default='employee', max_length=16),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(default='DE', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Bitte einen zweistelligen ISO-Ländercode angeben.')])),
                ('vat_id', models.CharField(blank=True, max_length=32)),
                ('tax_number', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='company/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp']), apps.core.models.validate_logo_size])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_company_profile')],
            },
        ),
    ]
