# Generated by Django 5.2.18 on 2026-10-06 17:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_catalog_sequence(apps, schema_editor):
    CatalogNumberSequence = apps.get_model("catalog", "CatalogNumberSequence")
    CatalogNumberSequence.objects.get_or_create(pk=1, defaults={"next_value": 1001})


def unseed_catalog_sequence(apps, schema_editor):
    CatalogNumberSequence = apps.get_model("catalog", "CatalogNumberSequence")
    CatalogNumberSequence.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('kind', models.CharField(choices=[('product', 'Artikel'), ('service', 'Leistung')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('hour', 'Stunde'), ('day', 'Tag'), ('piece', 'Stück'), ('flat', 'Pauschal')], max_length=16)),
                ('tax_rate', models.DecimalField(choices=[(Decimal('19.00'), '19 %'), (Decimal('7.00'), '7 %'), (Decimal('0.00'), '0 %')], decimal_places=2, max_digits=5)),
                ('tax_note', models.CharField(blank=True, max_length=240)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_catalog_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('item_number',),
            },
        ),
        migrations.CreateModel(
            name='CatalogAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Erstellt'), ('updated', 'Geändert'), ('archived', 'Archiviert')], max_length=16)),
                ('version', models.PositiveIntegerField()),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_audit_events', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CatalogNumberSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_value', models.PositiveBigIntegerField(default=1001)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_catalog_sequence')],
            },
        ),
        migrations.CreateModel(
            name='CatalogPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ('-valid_from', '-id'),
            },
        ),
        migrations.RunPython(seed_catalog_sequence, unseed_catalog_sequence),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['kind', 'archived_at'], name='catalog_cat_kind_acfef6_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['name'], name='catalog_cat_name_de33bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogprice',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='catalog_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='catalogprice',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='catalog_price_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='catalogprice',
            constraint=models.UniqueConstraint(fields=('item', 'valid_from'), name='catalog_price_unique_start'),
        ),
    ]
