# Generated by Django 5.2.18 on 2026-10-06 17:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_contact_sequence(apps, schema_editor):
    apps.get_model("crm", "ContactNumberSequence").objects.create(pk=1, next_value=1001)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('kind', models.CharField(choices=[('organization', 'Firma'), ('person', 'Person')], max_length=16)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('salutation', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('vat_id', models.CharField(blank=True, max_length=32)),
                ('leitweg_id', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('customer_number',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('billing', 'Rechnung'), ('shipping', 'Lieferung'), ('other', 'Sonstige')], default='billing', max_length=16)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('country_code', models.CharField(default='DE', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Bitte einen zweistelligen ISO-Ländercode angeben.')])),
                ('is_default', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.contact')),
            ],
            options={
                'ordering': ('kind', 'label', 'city'),
            },
        ),
        migrations.CreateModel(
            name='ContactAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Erstellt'), ('updated', 'Geändert'), ('archived', 'Archiviert')], max_length=16)),
                ('version', models.PositiveIntegerField()),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_audit_events', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='crm.contact')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactNumberSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_value', models.PositiveBigIntegerField(default=1001)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_contact_sequence')],
            },
        ),
        migrations.RunPython(create_contact_sequence, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salutation', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='crm.contact')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['kind', 'archived_at'], name='crm_contact_kind_f4cb23_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company_name'], name='crm_contact_company_a5ef07_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_contact_last_na_cda0e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'organization'), models.Q(('company_name', ''), _negated=True)), models.Q(('kind', 'person'), models.Q(('first_name', ''), _negated=True), models.Q(('last_name', ''), _negated=True)), _connector='OR'), name='contact_kind_required_names'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('contact', 'kind'), name='one_default_address_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='contactperson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact',), name='one_primary_contact_person'),
        ),
    ]
